from collections import Counter


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        """
        You are given two strings s and t.
        String t is generated by random shuffling string s and then add one more letter at a random position.
        Return the letter that was added to t.

        Parameters
        ----------
        s : str
            A string.
        t : str
            A string generated by randomly shuffling string s and then adding one more letter at a random position.

        Returns
        -------
        str
            Return the letter that was added.

        Examples
        --------

        Example 1:
        Input: s = "abcd", t = "abcde"
        Output: "e"
        Explanation: 'e' is the letter that was added.

        Example 2:
        Input: s = "", t = "y"
        Output: "y"
        """
        diff_counter = Counter(t) - Counter(s)
        # Get the unique differenciating character between s and t
        return list(diff_counter.keys())[0]


#################
### TEST CASE ###
#################

s = "abcd"
t = "abcde"

solution = Solution()
print(solution.findTheDifference(s=s, t=t))
